# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Specify the Ubuntu 25.04 box
  config.vm.box = "alvistack/ubuntu-25.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "DDoS Attacker"
    config.vm.boot_timeout = 1200
    # Set memory to 2GB (2048 MB)
    vb.memory = 2048
    # Set number of CPUs to 2
    vb.cpus = 2
    # Allow us to login via the VBox GUI
    vb.gui = true
    vb.customize ["modifyvm", :id, "--graphicscontroller", "VMSVGA"]
    vb.customize ["modifyvm", :id, "--vram", "256"] # Increase video memory
    vb.customize ["setextradata", :id, "GUI/LastGuestSizeHint", "1024,768"] # Set a preferred resolution hint
  end

  # Optional: Define a private network IP
  config.vm.network "private_network", ip: "192.168.56.3"

  # Forward ports via the NAT network (10.0.x.x)
  config.vm.network "forwarded_port", guest: 22, host: 22200

  # Provision the guest machine with a shell script
  config.vm.provision "shell", path: "provision.sh"
end
